apiVersion: v1
kind: PhJob
metadata:
  name: alfred
  description: "pharbers job description"
  labels:
    name: alfred
spec:
  containers:
    repository: local
    runtime: python3
    code: phmain.py
    config: phconf.yaml
    args:
      - key: extract_path
        value: "s3a://ph-stream/common/public/max_result/0.0.5/"
      - key: extract_file
        value: "Empty"
      - key: update_max
        value: "True"
    outputs:
      - key: a
        value: abcde
      - key: b
        value: 6789



