apiVersion: v1
kind: PhJob
metadata:
  name: job3_factor_optimize
  description: "pharbers job description"
  labels:
    name: job3_factor_optimize
    runtime: python3
spec:
  containers:
    repository: local
    runtime: python3
    command: "submit"
    timeout: 720.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: max_path
        value: 's3a://ph-max-auto/v0.0.1-2020-06-08/'
      - key: project_name
        value: 'Empty'
      - key: outdir
        value: 'Empty'
      - key: model_month_right
        value: 'Empty'
      - key: model_month_left
        value: 'Empty'
      - key: all_models
        value: 'Empty'
      - key: max_file
        value: 'Empty'
      - key: test
        value: 'False'
    outputs:
      - key: c
        value: abcde
      - key: d
        value: 6789



