apiVersion: v1
kind: PhJob
metadata:
  name: alfred
  description: "pharbers job description"
  labels:
    name: alfred
spec:
  containers:
    repository: local
    code: phmain.py
    config: phconf.yaml
    args:
      - key: max_path
        value: "/common/projects/max/"
      - key: max_path_local
        value: "s3a://ph-max-auto/v0.0.1-2020-06-08"
      - key: project_name
        value: "Sankyo"
      - key: model_month_left
        value: 201901
      - key: model_month_right
        value: 201912
      - key: paths_foradding
        value: ""
      - key: test_out_path
        value: "/user/ywyuan/max/"
      - key: need_test
        value: 0
    outputs:
      - key: a
        value: abcde
      - key: b
        value: 6789

