apiVersion: v1
kind: PhJob
metadata:
  name: job2_factor_raw
  description: "pharbers job description"
  labels:
    name: job2_factor_raw
    runtime: python3
spec:
  containers:
    repository: local
    runtime: python3
    code: phmain.py
    config: phconf.yaml
    args:
      - key: max_path
        value: 's3a://ph-max-auto/v0.0.1-2020-06-08/'
      - key: project_name
        value: 'Eisai'
      - key: outdir
        value: '202009'
      - key: model_month_right
        value: '201912'
      - key: model_month_left
        value: '201901'
      - key: all_models
        value: '固力康'
      - key: max_file
        value: 'MAX_result_201701_202009_city_level'
    outputs:
      - key: c
        value: abcde
      - key: d
        value: 6789



