apiVersion: v1
kind: PhDag
metadata:
  name: Auto_new_add_test
  description: "pharbers job description"
  labels:
    name: Auto_new_add_test
spec:
  description: "A Max Auto Job Example"
  start_date: 1 # if you don't understand, don't touch it
  schedule_interval: "None" # if you don't understand, don't touch it
  email: ['airflow@example.com']
  email_on_failure: False
  email_on_retry: False
  retries: 1
  retry_delay: "minutes=5"
  owner: ywyuan
  dag_id: Auto_new_add_test
  dag_tag: Max
  dag_timeout:  # minutes
  jobs:
    - name: job3_new1_template
    - name: job3_new2_dict
    - name: job3_new3_add
  linkage:
    - "job3_new1_template >> job3_new2_dict >> job3_new3_add"

