apiVersion: v1
kind: PhJob
metadata:
  name: alfred
  description: "pharbers job description"
  labels:
    name: alfred
spec:
  containers:
    repository: local
    code: phmain.py
    config: phconf.yaml
    args:
      - key: max_path
        value: "/common/projects/max/"
      - key: project_name
        value: "Sankyo"
      - key: cpa_gyc
        value: True
      - key: test_out_path
        value: "/user/ywyuan/max/"
      - key: need_test
        value: 0
    outputs:
      - key: a
        value: abcde
      - key: b
        value: 6789
