apiVersion: v1
kind: PhJob
metadata:
  name: alfred
  description: "pharbers job description"
  labels:
    name: alfred
spec:
  containers:
    repository: local
    code: phmain.py
    config: phconf.yaml
    args:
      - key: uni_path
        value: "/common/projects/max/Sankyo/universe_base"
      - key: cpa_pha_mapping_path
        value: "/common/projects/max/Sankyo/cpa_pha_mapping"
      - key: raw_data_path
        value: "/common/projects/max/Sankyo/raw_data"
      - key: std_names
        value: "PHA, ID, Year, Month, Molecule, Brand, Form, Specifications, Pack_Number, Manufacturer, Sales, Units, Province, City, Corp, Route"
      - key: cpa_gyc
        value: True
      - key: raw_data_job1_out_path
        value: "/user/ywyuan/max/Sankyo/raw_data_job1_out"       
    outputs:
      - key: a
        value: abcde
      - key: b
        value: 6789
