apiVersion: v1
kind: PhJob
metadata:
  name: alfred
  description: "pharbers job description"
  labels:
    name: alfred
spec:
  containers:
    repository: local
    runtime: python3
    code: phmain.py
    config: phconf.yaml
    args:
      - key: max_path
        value: "s3a://ph-max-auto/v0.0.1-2020-06-08/"
      - key: extract_path
        value: "s3a://ph-stream/common/public/max_result/0.0.5/"
      - key: project_name
        value: "Empty"
      - key: max_path_list
        value: "Empty"
      - key: out_dir
        value: "Empty"
    outputs:
      - key: a
        value: abcde
      - key: b
        value: 6789
