apiVersion: v1
kind: PhJob
metadata:
  name: alfred
  description: "pharbers job description"
  labels:
    name: alfred
spec:
  containers:
    repository: local
    code: phmain.py
    config: phconf.yaml
    args:
      - key: max_path
        value: "s3a://ph-max-auto/v0.0.1-2020-06-08/"
      - key: project_name
        value: "AZ"
      - key: out_path
        value: "s3a://ph-max-auto/v0.0.1-2020-06-08/"
      - key: out_dir
        value: "outlier"
      - key: doi
        value: "AZ16"
      - key: product_input
        value: "普米克令舒, Others-Pulmicort, 益索"
      - key: cities
        value: "长春市,长沙市,成都市"
      - key: sql_content2
        value: "select `mkt_vol`, `scen_id`, `scen`, `city`, `num_ot`, `vol_ot`, stack(3, '普米克令舒', `普米克令舒`, 'Others-Pulmicort', `Others-Pulmicort`, '益索', `益索`) as (`poi`, `poi_vol` ) from  v_pivot"
    outputs:
      - key: a
        value: abcde
      - key: b
        value: 6789

