apiVersion: v1
kind: PhJob
metadata:
  name: alfred
  description: "pharbers job description"
  labels:
    name: alfred
spec:
  containers:
    repository: local
    code: phmain.py
    config: phconf.yaml
    args:
      - key: max_path
        value: "/common/projects/max/"
      - key: max_path_local
        value: "s3a://ph-max-auto/v0.0.1-2020-06-08"
      - key: project_name
        value: "Sankyo"
      - key: minimum_product_columns
        value: "Brand, Form, Specifications, Pack_Number, Manufacturer"
      - key: minimum_product_sep
        value: ""
      - key: minimum_product_newname
        value: "min1"
      - key: need_cleaning_cols
        value: "Molecule, min1, Route, Corp"
      - key: test_out_path
        value: "/user/ywyuan/max/"
      - key: need_test
        value: 0
    outputs:
      - key: a
        value: abcde
      - key: b
        value: 6789
